services:
  - type: web
    name: saajjewels-backend
    env: node
    plan: free
    buildCommand: cd express_backend && npm install
    startCommand: cd express_backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  